### ISSUE TITLE
Last Spawn Time methodology is incorrect

### ISSUE THREAD

**Issue by ctdgunner** [Cyborger1/marks-of-grace-counter#1]
Last spawn time starts counting from 0 from the game tick where the mark of grace is first seen. This isn't correct. The game only rolls the chance when a lap is completed. There should be a background timer that starts counting from the most recent lap completion and then commits this time to "last spawn" when it detects a mark. this will allow for tick perfectly predicting the 3 minute cooldown when farming marks.

**Comment by ctdgunner** [comment]
[John Turner](https://www.youtube.com/@johnturner7313) can explain this far better than I can: https://www.youtube.com/watch?v=ovqOB2LeHG4&list=PLOJsCHOKSDyLsUjhYjU-NSttmqZ5L3V5G&index=3

Additional detail is on the [Wiki: Timing Marks](https://oldschool.runescape.wiki/w/Mark_of_grace#Timing_Marks)

**Comment by Cyborger1** [comment]
I added something that should work for you, however I left the alternate timing method off by default to not change the current behavior for existing users.

Once the above plugin hub pull request is merged, let me know if this is ok. If you have a plugin dev environment set up you may pull this repo and try it early as well.

**Comment by Cyborger1** [comment]
Change was merged, please tick the "Use Lap Finish Mark Timing" config option and let me know if everything's good.
![image](https://github.com/user-attachments/assets/ab911963-6991-4a8e-9c43-e3a611c518d1)

**Comment by ctdgunner** [comment]
Yes this works as expected

**Comment by Cyborger1** [comment]
If everything's good then I'm closing this issue, have a good day 🙂
